### ISSUE TITLE
lark.exceptions.UnexpectedToken: Unexpected token Token(RPAR, ')') 

### ISSUE THREAD

**Issue by schosterbarak** [amplify-education/python-hcl2#14]
this exception happens for parsing a file with `file(x)` function like this one:
https://www.terraform.io/docs/configuration/functions/file.html

**Comment by schosterbarak** [comment]
hey @aoskotsky-amplify any ideas how can i workaround this one?

**Comment by aoskotsky-amplify** [comment]
What value are you putting in as the argument to `file()`?

**Comment by schosterbarak** [comment]
path to a yaml file
something like:
`file("${path.module}/hello.yaml")`

**Comment by aoskotsky-amplify** [comment]
Can you add an example hcl2 file thats failing? I tried adding `file("${path.module}/hello.yaml")` in one of mine and i'm not getting that error

**Comment by schosterbarak** [comment]
getting a similar error for:
<class 'tuple'>: ("Unexpected token Token(__ANON_1, '# add a CIDR block here\\n') at line 187, column 19.\nExpected one of: \n\t* LBRACE\n\t* LSQB\n\t* IDENTIFIER\n\t* BANG\n\t* MINUS\n\t* LPAR\n\t* NULL\n\t* __ANON_10\n\t* DECIMAL\n\t* __ANON_9\n\t* STRING_LIT\n\t* TRUE\n\t* FALSE\n",)
for

`resource "aws_security_group" "allow_tls" {
  name        = "allow_tls"
  description = "Allow TLS inbound traffic"
  vpc_id      = "${aws_vpc.main.id}"

  ingress {
    # TLS (change to whatever ports you need)
    from_port   = 443
    to_port     = 443
    protocol    = "tcp"
    # Please restrict your ingress to only necessary IPs and ports.
    # Opening to 0.0.0.0/0 can lead to security vulnerabilities.
    cidr_blocks = # add a CIDR block here
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
    prefix_list_ids = ["pl-12c4e678"]
  }
}`

**Comment by schosterbarak** [comment]
Getting similar parsing error for:

```
resource "aws_security_group" "test" {
  vpc_id = module.dev_vpc.vpc_id
  ingress {
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
    cidr_blocks = [local.vpc.config.vpc_cidr, local.vpc.config.lnk_cidr]
  }
  ingress {
    protocol    = "tcp"
    from_port   = 80
    to_port     = 80
    cidr_blocks = [local.vpc.config.vpc_cidr, local.vpc.config.lnk_cidr]
  }
  ingress {
    protocol    = "tcp"
    from_port   = 22
    to_port     = 22
    cidr_blocks = [local.vpc.config.vpc_cidr, local.vpc.config.lnk_cidr]
  }
  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
  tags  = merge(local.tags_default, {
    Name: "${local.vpc.config.vpc_nickname} test"
  })
}
```

**Comment by schosterbarak** [comment]
i think it's the ':'

**Comment by aoskotsky-amplify** [comment]
I don't think you are allowed to use `:` in hcl objects. It should be `Name = "${local.vpc.config.vpc_nickname} test"`. Is that config actually working in Terraform?

**Comment by m-wynn** [comment]
I believe this is a Terraform 0.11 vs Terraform 0.12 issue.  (See https://www.terraform.io/upgrade-guides/0-12.html#attributes-vs-blocks)

The [0.11](https://www.terraform.io/docs/configuration-0-11/syntax.html) syntax guide describes a map using colons, while [0.12](https://www.terraform.io/docs/configuration/functions/merge.html) only has maps with equals signs.

**Comment by aoskotsky-amplify** [comment]
Closing this issue since Terraform 0.11 syntax isn't supported by hcl2. Feel free to reopen this issue if it happens in your Terraform 0.12 configs
