### ISSUE TITLE
Unexpected token Token(COLON, ':') in ternary operation

### ISSUE THREAD

**Issue by aabouzaid** [amplify-education/python-hcl2#26]
Hello,

Thanks for that heplful project.

Using quotes within ternary operation fails if there is a var in it.

**This works:**  (hcl2 able to parse it)
```
resource "aws_instance" "web" {
  subnet = "${var.env == "production" ? var.prod_subnet : var.dev_subnet}"
}
```

Also this:
```
resource "aws_instance" "web" {
  subnet = "${var.env == "production" ? ${var.prod_subnet}-xyz : var.dev_subnet}"
}
```

**This doesn't work:** (even it's accepted in Terraform 12)
```
resource "aws_instance" "web" {
  subnet = "${var.env == "production" ? "${var.prod_subnet}-xyz" : var.dev_subnet}"
}
```

Any workaround without change the actual TF files?

**Comment by aoskotsky-amplify** [comment]
Looks like there is an issue in the parser with nested interpolation strings `${..}`. Might be tricky to fix. Feel free to send a PR if you if you have a fix. In this case though, you can replace that line with `subnet = var.env == "production" ? "${var.prod_subnet}-xyz" : var.dev_subnet`

**Comment by thehesiod** [comment]
there's another case as well: 
```
resource "datadog_monitor" "tf_thing" {
  for_each = {
    "thing2" : 12 * 60 * 60,
  }
}
```
yields 
`Unexpected token Token(COLON, ':') at line 4, column 19.`

**Comment by michaelDadurian** [comment]
Having the same issue with Terraform v0.13.5. Line is ```value = "https://gateway.${var.stage == "production" ? "prod.com" : var.stage == "staging" ? "${var.env}.qa.com" : "${var.env}.alpha.com"}"```

**Comment by sahilsk** [comment]
I confirm that these issues are no longer in latest version: 4.2.x
