### ISSUE TITLE
Support for .tf.json

### ISSUE THREAD

**Issue by freddd** [amplify-education/python-hcl2#31]
Hi, 

Would it be possible to add support for `.tf.json`? We are currently looking into using a tool called [checkov](https://www.checkov.io/) to help identify cloud misconfigurations during build time, however as they use this library they only support `.tf` and I was asked to create an issue here when reaching out to them on slack. Ping @schosterbarak

For reference: 

- Issue at checkov: https://github.com/bridgecrewio/checkov/issues/315
- Terraform json: https://www.terraform.io/docs/configuration/syntax-json.html

**Comment by kapilt** [comment]
my two cents as an observer, this really isn't an issue for this python-hcl2. ie. this package parses hcl not json (for which stdlib works well), its a problem for checkov to solve.

**Comment by jackmclrtz** [comment]
I have not read the links from the OP, but I suspect the point they are making is that the structure this library creates (when written back out as json) is not valid terraform.
Terraform supports json files. In terraform 0.11, you can load with pyhcl and write back out as json and it builds fine. This is critical functionality for build-time code management.

But for python-hcl2, this does not work. E.g., if you have a count field in a resource, the numeric field gets turned into a list. I have not for-scienced that it always does it, but it does if the value for the count is an expression (e.g., count = length(var.serverlist) )
