### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by holgiosalos** [amplify-education/python-hcl2#43]
Hello @aoskotsky-amplify, @pbchekin, @ahlinc !

Hope you guys are fine.

I am seeing several PRs that have been waiting for review for a long time. I'm wondering if maybe this project is closed and if so, if there are other alternatives that we can use.

Thanks 😄

**Comment by aoskotsky-amplify** [comment]
Hi. Sorry, I've been busy but the project is still active. I'll try to review the open PRs as soon as possible.
