### ISSUE TITLE
Incorrectly transforms attributes into lists

### ISSUE THREAD

**Issue by raymondbutcher** [amplify-education/python-hcl2#6]
Hi,

I was excited to try this package but it seems to turn everything into a list. There is a test for this behaviour, which I think is wrong:

https://github.com/amplify-education/python-hcl2/blob/a4b29a76e34bbbd4bcac8d073f96392f451f79b3/test/helpers/terraform-config/vars.auto.tfvars#L1

https://github.com/amplify-education/python-hcl2/blob/a4b29a76e34bbbd4bcac8d073f96392f451f79b3/test/helpers/terraform-config-json/vars.auto.json#L2-L4

I think the JSON should be:

```json
"foo": "bar",
```

https://github.com/hashicorp/hcl2#information-model-and-syntax has examples with top-level strings.

I would like to get confirmation that this is a bug before I have a go at fixing it and trying to use this in my project. Thanks!

**Comment by aoskotsky-amplify** [comment]
This is actually intentional https://github.com/hashicorp/hcl2/blob/master/hcl/json/spec.md#blocks. It's possible to have duplicate block fields in HCL2. For example the `iam_policy_document` data source can have multiple `statement` fields. https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html. 

This forces me to convert blocks into arrays because json dicts can't have duplicate fields. It isn't ideal though. I'm open to any alternative approaches.

**Comment by raymondbutcher** [comment]
I'll need to read the spec and related specs a bit more but I think this falls under https://github.com/hashicorp/hcl2/blob/master/hcl/json/spec.md#attributes which aren't meant to be arrays.

**Comment by tbugfinder** [comment]
Would we expect that the `terraform-config-inspect variables.tf` creates the same output as `hcl2tojson variables.tf` ?
I also noticed that `hcl2tojson` adds arrays althoughs the hashicorp tool doesn't.

**Comment by monester** [comment]
@aoskotsky-amplify it is correct only for blocks, but for values is not possible to have assignment of same variable in one block
```hcl
data "aws_iam_policy_document" "example" {
  statement {}
  statement {}
  statement {}
}
```
is valis but this code
```hcl
module  "own_module" {
 foo = "bar"
 foo = "bar2"
}
```
is not valid. Error raised:
```
Error: Attribute redefined

  on main.tf line 21, in module "own_module":
  21:   foo = "bar2"
```

**Comment by radcool** [comment]
I would say @monester is correct, as according to https://github.com/hashicorp/hcl/blob/hcl2/hclsyntax/spec.md#attribute-definitions:

"Each distinct attribute name may be defined no more than once within a single body."

**Comment by jackmclrtz** [comment]
This seems to happen all over the place. For example, I have an ec2 resource that uses the count field. The value is an expression (count = length(var.serverlist) ). 
But python-hcl2 turns this into a list (count = [ "length(var.serverlist)" ] ). Terraform chokes on this if you write this back out as json. This type of transformation is critical to my pipeline.
