### ISSUE TITLE
Incorrectly converting maps to lists

### ISSUE THREAD

**Issue by nadenf** [amplify-education/python-hcl2#66]
I have the following tfvars which I am trying to parse:
```
executors = {
  launch = {
    time         = "01:00"
  }
}
```

And your library is converting it to:
```
'executors': [{'launch': {'time': '01:00' }}
```

Which looks similar to other issues about it converting everything to lists.

**Comment by aoskotsky-amplify** [comment]
I believe this was fixed in 3.0.0. Feel free to reopen if you are still seeing this issue
