### ISSUE TITLE
Errors parsing for loop (or maybe nested for loop)

### ISSUE THREAD

**Issue by mikeurbanski1** [amplify-education/python-hcl2#86]
When parsing [this](https://raw.githubusercontent.com/terraform-google-modules/terraform-google-iam/a647179a1d839cb67816b6964a14446eb03b44b1/modules/helper/main.tf) file, we get the following error:

```
lark.exceptions.UnexpectedToken: Unexpected token Token('__ANON_0', '\n') at line 38, column 36.
Expected one of:
	* COLON
	* STAR
	* PERCENT
	* SLASH
	* __ANON_9
	* __ANON_8
	* __ANON_6
	* QMARK
	* __ANON_5
	* MORETHAN
	* PLUS
	* __ANON_4
	* MINUS
	* __ANON_7
	* LESSTHAN
```

The problematic lines appear to be:

```
bindings_by_role = distinct(flatten([
    for name in local.real_entities
    : [
      for role, members in var.bindings
      : { name = name, role = role, members = members }
    ]
  ]))
```

Converting the syntax to this seems to fix it (of course, it's a third party module, so we can't actually change it):

```
bindings_by_role = distinct(flatten([
    for name in local.real_entities: [
      for role, members in var.bindings: { name = name, role = role, members = members }
    ]
  ]))
```

Note that this file also hits the [multi-line ternary issue](https://github.com/amplify-education/python-hcl2/issues/77) towards the bottom.

**Comment by aoskotsky-amplify** [comment]
This should be fixed with https://github.com/amplify-education/python-hcl2/pull/92. Let me know if you are still seeing this issue
