### ISSUE TITLE
Why 2 pip projects

### ISSUE THREAD

**Issue by Fran-Rg** [amplify-education/python-hcl2#88]
I just found a really hidden conflict caused by the project being available on pypi under 2 different names:
* https://pypi.org/project/bc-python-hcl2/
* https://pypi.org/project/python-hcl2/

I've used 2 tools and each one refers to a different pip source. Each one requiring different version. It's all fine at pip install.
But when running, "import hcl2" one of the tool imports the wrong one and it fails

**Comment by mcdonnnj** [comment]
@Fran-Rg What you've stumbled into is another org publishing their own fork to PyPi (I'm assuming for the convenience of installing with pip). You can see the `bc-python-hcl2` source at https://github.com/bridgecrewio/python-hcl2.

**Comment by Fran-Rg** [comment]
Hi yes, I raised a ticket with them as well. https://github.com/bridgecrewio/checkov/issues/2317
I don't think there's any solution available from here
