### ISSUE TITLE
Support token Metadata like line & col numbers

### ISSUE THREAD

**Issue by jatin-arora2** [amplify-education/python-hcl2#91]
**Context**:
We are using this library for developing a small suite of utilities for terraform files to validate them according to some business rules. For e.g having a list of whitelisted resources, some standard configurations for resources etc. We found that we needed to add some exclusions for some of these checks at the object level i.e specific resources, data sources etc. in a file. So we thought of something very similar to a linter of sorts, where you can put a comment over a piece of resource and it would be ignored during the validation. 

**Problem**:
The library does not expose any metadata or comments/other token locations to figure out the bounds and context of a comment and the next resource.

**Possible Idea/Enhancement**:
Would it be possible to expose these attributes per token if required?  

Open to ideas and suggestion. Also happy to contribute if it is feasible 😄 .

**Comment by htorianik** [comment]
Solved in #120
